micronaut:
  server:
    port: 8082
    cors:
      enabled: true
      configurations:
        web:
          exposedHeaders:
            - Content-Type
            - Authorization
            - '*'
  io:
    watch:
      paths: "src/jvmMain"
      restart: true
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/static/**"
        paths: "classpath:data"
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          openid:
            issuer: "https://accounts.google.com"
          client-credentials:
            additional-request-params:
              prompt: consent
    endpoints:
      logout:
        get-allowed: true
    redirect:
      login-success:
        /auth/login
      login-failure:
        /auth/login
      logout:
        /auth/login
      unauthorized:
        url: /auth/login
        enabled: true
jackson:
  serialization:
    writeDatesAsTimestamps: false
blog:
  aws:
    localstack: "true"
    endpoint: "http://localhost:4566"
    credentials:
      username: "test"
      secretAccessKey: "test"
  template:
    default-template: "home.ftl"
aws:
  region: "eu-central-1"
