micronaut:
  server:
    port: 8082
    cors:
      enabled: true
      configurations:
        web:
          exposedHeaders:
            - Content-Type
            - Authorization
            - '*'
  io:
    watch:
      paths: "src/jvmMain"
      restart: true
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/static/**"
        paths: "classpath:data"
jackson:
  serialization:
    writeDatesAsTimestamps: false
blog:
  aws:
    localstack: "true"
    endpoint: "http://localhost:4566"
    credentials:
      username: "test"
      secretAccessKey: "test"
  template:
    default-template: "home.ftl"
aws:
  region: "eu-central-1"
